# Generated by Django 4.1.1 on 2022-09-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(default='', max_length=200)),
                ('category', models.CharField(default='', max_length=200)),
                ('stock', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
