# Generated by Django 4.1.1 on 2022-09-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmonitor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('location', models.CharField(default='', max_length=100)),
                ('createdAt', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
