version: "3"
   
services:  
  web:
    build: .
    command: python manage.py runserver 8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_DB=stock_monitor
   