pipeline {
    agent {
        docker {
            image 'node:16.13.1-alpine'
            reuseNode true
        }
    }

    stages {

        stage('Check env') {
            steps {
                
                sh '''
                node --version
                echo "home1 $HOME"
                docker --version
                python3 --version
                pip --version
                virtualenv --version
                '''
            }
            
        }


        stage('Build') {
            steps {
                echo 'Installing'
                sh '''
                pip install -r requirements.txt 
                '''
            }
        }

        // stage('Test') {
        //     steps {
        //         echo 'Testing'
        //         sh 'npm run test'
        //     }
        // }

        // stage('Deploy') {
        //     steps {
        //         script {
        //             echo 'Deploying'
        //             customImage = docker.build("stock-monitor-api-python:${env.BUILD_ID}")
        //             customImage.inside {
        //                 sh '''
        //                 docker-compose up
        //                 '''
        //             }
        //         }
        //     }
        // }
    }
}
