pipeline {
    agent any

    stages {

        stage('Check env') {
            steps {
                
                sh '''
                echo "home1 $DJANGO_KEY"
                docker --version
                python3 --version
                pip --version
                virtualenv --version
                '''
            }
            
        }


        stage('Build') {
            steps {
                echo 'Building'
                sh '''
                cd stockmonitorapi
                docker build sm-api -f ./Dokerfile /
                --build-arg DJANGO_KEY=${DJANGO_KEY} /
                --build-arg MONGO_USER=${MONGO_USER} /
                --build-arg MONGO_PASSWORD=${MONGO_PASSWORD} /
                --build-arg MONGO_HOST=${MONGO_HOST}  . 
                cd ..
                '''
            }
        }

        // stage('Run') {
        //     steps {
        //         echo 'Starting app'
        //         sh '''
        //         docker run -itd --name smapi-app -p 8000:8000 sm-api 
        //         '''
        //     }
        // }
    }
}
